version: "3.7"
services:
  bot:
    build:
      context: .
    env_file: .env
    container_name: aiobot
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command: sh -c "python bot.py & uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload"
